import Head from 'next/head'
import dynamic from 'next/dynamic'
import 'leaflet/dist/leaflet.css'
import 'react-leaflet-markercluster/dist/styles.min.css'
function Home() {
  const MapWithNoSSR = dynamic(() => import('../components/map'), { ssr: false })
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <MapWithNoSSR />
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
